version: '2.4'

networks: 
  docker_proxy_internal:
    name: docker_proxy_internal
    internal: true
    ipam:
      driver: default
      config:
        - subnet: "${DOCKER_PROXY_IP_SUBNET:-192.168.240}.0/24"
    driver_opts:
      com.docker.network.bridge.name: docker-proxy0

services:
  docker-socket-proxy:
    image: tecnativa/docker-socket-proxy
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=10
      - INFO=1
    networks:
      docker_proxy_internal:
        ipv4_address: "${DOCKER_PROXY_IP_SUBNET:-192.168.240}.2"
    runtime: runc
    mem_limit: 32M
  ### Filebeat  ###
  filebeat:
    image: filebeat:latest
    container_name: filebeat
    hostname: mydockerhost
    restart: unless-stopped
    # environment:
    #   - ELASTICSEARCH_HOSTS=elasticsearch1:9200,elasticsearch2:9200
    # labels:
    #   co.elastic.logs/enabled: "false"
    #   # For Rancher
    #   io.rancher.container.agent.role: environmentAdmin
    #   io.rancher.container.create_agent: 'true'
    #   io.rancher.scheduler.global: 'true'
    networks:
      docker_proxy_internal:
        ipv4_address: "${DOCKER_PROXY_IP_SUBNET:-192.168.240}.3"
      default:
    volumes:
    - /var/lib/docker/containers/:/var/lib/docker/containers:ro
    - /var/log:/var/log:ro
    - /var/log/filebeat:/var/log/filebeat
    extra_hosts: 
      - "docker-socket-proxy:${DOCKER_PROXY_IP_SUBNET:-192.168.240}.2"
    mem_limit: 32M
    group_add:
    - adm
